version: "2"

services:

  postgres:
    env_file:
      - env
    restart: always
    image: postgres:latest
    volumes:
      - data_postgres:/var/lib/postgresql
    ports:
      - "5432:5432"

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"

  backend:
    env_file:
      - env
    restart: always
    build: ./backend
    depends_on:
      - postgres
      - nginx
    command: uwsgi --http-socket=:8000 --pp=/usr/src/app --wsgi-file=app.py --callable=wsgi_app --master

volumes:
  data_postgres:
    external: false
